import { Fx } from "./module/GameStart/GameAppStart";

const {ccclass, property, requireComponent} = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {

    @property(false)
    localTest: boolean = false;

    @property("")
    clientTestVersion: string = "1.0.0";

    @property(cc.Label)
    testVersion: cc.Label = null;

    start () {
        Fx.init();
        Fx.GameConfig.init(true);
        // Fx.GameConfig.init(true);
        // Fx.AudioManager.Instance.init();
        this.testVersion.string = this.clientTestVersion;
    }

    //开始游戏，跳转至引导页面
    startGame(){
        cc.director.loadScene("GameScene");
        // cc.director.loadScene("GuideScene");
    }
    //备用，用来测试跳转 指定关卡
    clickBtn(event,data){
        Fx.GameConfig.GM_INFO.custom = parseInt(data);
        cc.director.loadScene("GameScene");
    }   
    //打开排行榜
    openRank(){
        cc.director.loadScene("RankScene");
    }
    
    protected update(dt: number): void {
    }
}
